[workspace]
resolver = "2"
members = [
    "chat",
    "combatlog",
    "lifestate",
    "wards",
    "positions"
]

[profile.dev]
opt-level = 2

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = "symbols"
