[package]
name = "wards"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
source2-demo = { path = "../../source2-demo", features = ["dota"] }
hashbrown = "0.14"
memmap2 = "0.9.4"
anyhow = "1.0"